# -*- coding: utf-8 -*-
"""pertemuan 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vPp0U-Z5yrNmz37hbKUnQVkMIxQaKSQ

1. MEMBUAT ARRAY
"""

import array as arr
a =arr.array("1", [1, 2, 3])
print('the new created array is ;', end="")
for i in range(0, 3):
  print(a[1], en="")
print()
b = arr.array("d", [2.5, 3.2, 3.3])
print("\nThe new created array is :, end=")
for i in range(0, 3):
  print(b[1], end="")

"""2. MENAMBAHKAN ELEMEN KE ARRAY"""

import array as arr
a = arr.array('i', [1, 2 ,3])
print("array before insertion :", end=" ")
for i in range(0, 3):
  print(a[i], end=" ")
print()
a.insert(1, 4)
print("array after insertion :", end=" ")
for i in (a):
  print(i, end=" ")
print()
b = arr.array('d', [2.5, 3.2, 3.3])
print("array before insertion :", end=" ")
for i in range(0, 3):
  print(b[i], end=" ")
print()
b.append(4.4)
print("array after insertion :", end=" ")
for i in (b):
  print(i, end=" ")
print()

"""3. MENGAKSES ELEMEN ARRAY"""

import array as arr
a= arr.array('i', [1, 2, 3, 4, 5, 6])
print("acces element is: ", a[0])
print("acces element is: ", a[3])

b= arr.array('d', [2.5, 3.2, 3.5])
print("acces element is: ", b[1])
print("acces element is: ", b[2])

"""4. MENGHAPUS ELEMEN ARRAY"""

import array
arr = array.array ('i', [1, 2, 3, 1, 5])
print("the new created array is :", end=" ")
for i in range(0,5):
  print(arr[i], end="")

print("\r")
print("the pooped elemen is : ", end=" ")
print(arr.pop(2))
print('the array after pooping is:', end=" ")
for i in range(0, 4):
  print(arr[i], end=" ")

print("\r")
print('the array after removing is:', end=" ")
for i in range(0, 4):
  print(arr[i], end=" ")

"""5. PEMOTONGAN ELEMEN ARRAY"""

import array as arr
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a= arr.array('i', l)
print('initial array')
for i in (a):
  print(i, end=" ")
sliced_array = a[3:8]
print('\nSlicing elements in range 3-8: ')
print(sliced_array)
sliced_array= a[5:]
print('\nElements sliced from 5th '
  "element till the end")
print(sliced_array)
sliced_array= a[:]
print("\nPrinting all element using slice operation:")
print(sliced_array)

"""6. MENGUBAH ELEMEN ARRAY"""

import array
arr= array.array("i", [1,2,3,1,2,5])
print("array before updation : ", end=" ")
for i in range(0, 6):
  print(arr[i], end=" ")

print('\r')
arr[2]= 6
print("array after updation : ", end=" ")
for i in range(0, 6):
  print(arr[1], end=" ")
print()
arr[4] = 8
print("array after updation :", end=" ")
for i in range(0, 6):
  print(arr[i], end=" ")

"""7. BERBAGI OPERASI ARRAY"""

import array
my_array = array.array('i', [1, 2, 3, 4, 2, 5, 2])

#menghitung elemen array
count = my_array.count(2)
print("Number of occurrences of 2:", count)

"""8. MEMBALIK ELEMEN PADA ARRAY"""

import array
my_array = array.array('i', [1, 2, 3, 4, 2, 5, 2])

#menghitung elemen array
count = my_array.count(2)
print("Number of occurrences of 2:", count)

# Membalik Elemen Array
print("Original array:", *my_array)
my_array.reverse()
print("Reversed array:", *my_array)

"""9. Extend dalam array"""

import array as arr
a = arr.array('i', [1, 2, 3, 4, 5])
print("Array before extend:", end=" ")
for i in range(0,5):
  print(a[i], end=" ")

a.extend([6, 7, 8, 9, 10])
print('\nThe array after extend:', end=" ")
for i in range(0, 10):
  print(a[i], end=" ")
print()

import array as arr
a = arr.array('i', [1, 2, 3, 4, 5, 6])
print("Array before extend:", end=" ")
for i in range(0,6):
  print(a[i], end=" ")

a.extend([7, 8, 9, 10, 11, 12])
print('\nThe array after extend:', end=" ")
for i in range(0, 12):
  print(a[i], end=" ")
print()

b = arr.array('d', [2.1,2.2,2.3,2.4,2.5,2.6])
print("Array before extend:", end=" ")
for i in range(0,6):
  print(b[i], end=" ")

b.extend([2.6,2.7,2.8,2.8])
print('\nThe array after extend:', end=" ")
for i in range(0, 10):
  print(b[i], end=" ")
print()